config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :categoriys
  resources :products
  resources :product_categories
  resources :categoryers
  root "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end
 

app/models/categoriy.rb
class Categoriy < ApplicationRecord
    has_many :categoryers, dependent: :destroy
end
 

app/controllers/categoriys_controller.rb
class CategoriysController < ApplicationController
  before_action :set_categoriy, only: %i[ show edit update destroy ]

  # GET /categoriys or /categoriys.json
  def index
    @categoriys = Categoriy.all
  end
 
  # GET /categoriys/1 or /categoriys/1.json
  def show
  end

  # GET /categoriys/new
  def new
    @categoriy = Categoriy.new
  end

  # GET /categoriys/1/edit
  def edit
  end

  # POST /categoriys or /categoriys.json
  def create
    @categoriy = Categoriy.new(categoriy_params)

    respond_to do |format|
      if @categoriy.save
        format.html { redirect_to categoriy_url(@categoriy), notice: "Categoriy was successfully created." }
        format.json { render :show, status: :created, location: @categoriy }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @categoriy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categoriys/1 or /categoriys/1.json
  def update
    respond_to do |format|
      if @categoriy.update(categoriy_params)
        format.html { redirect_to categoriy_url(@categoriy), notice: "Categoriy was successfully updated." }
        format.json { render :show, status: :ok, location: @categoriy }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @categoriy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categoriys/1 or /categoriys/1.json
  def destroy
    @categoriy.destroy

    respond_to do |format|
      format.html { redirect_to categoriys_url, notice: "Categoriy was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_categoriy
      @categoriy = Categoriy.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def categoriy_params
      params.require(:categoriy).permit(:name)
    end
end

app/helpers/categoriys_helper.rb
module CategoriysHelper
end
 

app/views/categoriys/_categoriy.html.erb
<div id="<%= dom_id categoriy %>">
  <p>
    <strong>Name:</strong>
    <%= categoriy.name %>
  </p>

</div>
 

app/views/categoriys/_form.html.erb
<%= simple_form_for(@categoriy) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>
 

app/views/categoriys/edit.html.erb
<h1>Editing categoriy</h1>

<%= render "form", categoriy: @categoriy %>

<br>

<div>
  <%= link_to "Show this categoriy", @categoriy %> |
  <%= link_to "Back to categoriys", categoriys_path %>
</div>
 

app/views/categoriys/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Categoriys</h1>

<div id="categoriys">
  <% @categoriys.each do |categoriy| %>
    <%= render categoriy %>
    <p>
      <%= link_to "Show this categoriy", categoriy %>
    </p>
  <% end %>
</div>

<%= link_to "New categoriy", new_categoriy_path %>
  

app/views/categoriys/new.html.erb
<h1>New categoriy</h1>

<%= render "form", categoriy: @categoriy %>

<br>

<div>
  <%= link_to "Back to categoriys", categoriys_path %>
</div>
 

app/views/categoriys/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @categoriy %>

<div>
  <%= link_to "Edit this categoriy", edit_categoriy_path(@categoriy) %> |
  <%= link_to "Back to categoriys", categoriys_path %>

  <%= button_to "Destroy this categoriy", @categoriy, method: :delete %>
</div>
 