config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :categoriys
  resources :products
  resources :product_categories
  resources :categoryers
  root "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end
 

app/models/categoryer.rb
class Categoryer < ApplicationRecord
    belongs_to :categoriy
    has_many :product_categories
end
 

app/controllers/categoryers_controller.rb
class CategoryersController < ApplicationController
  before_action :set_categoryer, only: %i[ show edit update destroy ]

  # GET /categoryers or /categoryers.json
  def index
    @categoryers = Categoryer.all
    @categoriys = Categoriy.all

  end
 
  # GET /categoryers/1 or /categoryers/1.json
  def show
    @categoriys = Categoriy.all
    @products = Product.all
    @product_categories = ProductCategory.all
  end

  # GET /categoryers/new
  def new
    @categoryer = Categoryer.new
  end

  # GET /categoryers/1/edit
  def edit
  end

  # POST /categoryers or /categoryers.json
  def create
    @categoryer = Categoryer.new(categoryer_params)

    respond_to do |format|
      if @categoryer.save
        format.html { redirect_to categoryer_url(@categoryer), notice: "Categoryer was successfully created." }
        format.json { render :show, status: :created, location: @categoryer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @categoryer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categoryers/1 or /categoryers/1.json
  def update
    respond_to do |format|
      if @categoryer.update(categoryer_params)
        format.html { redirect_to categoryer_url(@categoryer), notice: "Categoryer was successfully updated." }
        format.json { render :show, status: :ok, location: @categoryer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @categoryer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categoryers/1 or /categoryers/1.json
  def destroy
    @categoryer.destroy

    respond_to do |format|
      format.html { redirect_to categoryers_url, notice: "Categoryer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_categoryer
      @categoryer = Categoryer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def categoryer_params
      params.require(:categoryer).permit(:name, :categoriy_id)
    end
end

app/helpers/categoryers_helper.rb
module CategoryersHelper
end
 

app/views/categoryers/_categoryer.html.erb
<div id="<%= dom_id categoryer %>">

<p>
  <strong>Category</strong>
  <%= link_to categoryer.categoriy.name, categoryer.categoriy, class: "ashow"%>><%= link_to categoryer.name, categoryer, class: "ashow" %>
  </p>

<% categoryer.product_categories.each do |product_categorier| %>

<p>
<%= link_to product_categorier.name, product_categorier, class: "ashow" %>

</p>
 

<% end %>
</div>


<style>
.ashow{
   
}
</style>
<% categoryer.product_categories.each do |product_categorier| %>
<div class="container mt-5 mb-3">
    <div class="row">
      <% @products.each do |product| %>  
<% if product.product_category.name == product_categorier.name  %>
      
        <div class="col-md-4">
            <div class="card p-3 mb-2">
                <div class="d-flex justify-content-between">
                    <div class="d-flex flex-row align-items-center">
                        <div class="icon"> <i class="bx bxl-dribbble"></i> </div>
                        <div class="ms-2 c-details">
                            <h6 class="mb-0"><%= product.name %></h6> 
                        </div>
                    </div>
                    <div class="badge"> <span>Product</span> </div>
                </div>
                <div class="mt-5">
                    <h6 class="heading"><%= product.description %></h6>
                    <div class="mt-5">
                        <div class="mt-3"> <span class="text1"><%= product.price %>$</span> </div>
                    </div>
                    <%= link_to product.product_category.categoryer.categoriy.name, product.product_category.categoryer.categoriy %>><%= link_to product.product_category.categoryer.name,product.product_category.categoryer %>><%= link_to product.product_category.name, product.product_category, class: "ashow" %>
                </div>
            </div>
        </div>
<% end %>
<% end %>

<% end %>

    </div>
</div>

app/views/categoryers/_form.html.erb
<%= simple_form_for(@categoryer) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-inputs">
    <%= f.association :categoriy %>
  </div>
 
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categoryers/edit.html.erb
<h1>Editing categoryer</h1>

<%= render "form", categoryer: @categoryer %>

<br>

<div>
  <%= link_to "Show this categoryer", @categoryer %> |
  <%= link_to "Back to categoryers", categoryers_path %>
</div>
 

app/views/categoryers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Categoryers</h1>

<div id="categoryers">
  <% @categoryers.each do |categoryer| %>
    <%= render categoryer %>
    <p>
      <%= link_to "Show this categoryer", categoryer %>
    </p>
  <% end %>
</div>

<%= link_to "New categoryer", new_categoryer_path %>
 

app/views/categoryers/new.html.erb
<h1>New categoryer</h1>

<%= render "form", categoryer: @categoryer %>

<br>

<div>
  <%= link_to "Back to categoryers", categoryers_path %>
</div>
 

app/views/categoryers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @categoryer %>


 