config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :categoriys
  resources :products
  resources :product_categories
  resources :categoryers
  root "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end
 

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :categoryer
  has_many :products
end
 

app/controllers/product_categories_controller.rb
class ProductCategoriesController < ApplicationController
  before_action :set_product_category, only: %i[ show edit update destroy ]

  # GET /product_categories or /product_categories.json
  def index
    @product_categories = ProductCategory.all
    @products = Product.all
    @categoriys = Categoriy.all

  end
 
  # GET /product_categories/1 or /product_categories/1.json
  def show
    @products = Product.all
    @categoriys = Categoriy.all
  end

  # GET /product_categories/new
  def new
    @product_category = ProductCategory.new
    @categoriys = Categoriy.all
  end

  # GET /product_categories/1/edit
  def edit
  end

  # POST /product_categories or /product_categories.json
  def create
    @product_category = ProductCategory.new(product_category_params)

    respond_to do |format|
      if @product_category.save
        format.html { redirect_to product_category_url(@product_category), notice: "Product category was successfully created." }
        format.json { render :show, status: :created, location: @product_category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_categories/1 or /product_categories/1.json
  def update
    respond_to do |format|
      if @product_category.update(product_category_params)
        format.html { redirect_to product_category_url(@product_category), notice: "Product category was successfully updated." }
        format.json { render :show, status: :ok, location: @product_category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_categories/1 or /product_categories/1.json
  def destroy
    @product_category.destroy

    respond_to do |format|
      format.html { redirect_to product_categories_url, notice: "Product category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_category
      @product_category = ProductCategory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_category_params
      params.require(:product_category).permit(:name, :categoryer_id)
    end
end

app/helpers/product_categories_helper.rb
module ProductCategoriesHelper
end
 

app/views/product_categories/_form.html.erb
<%= simple_form_for(@product_category) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.association :categoryer %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %> 
 

app/views/product_categories/_product_category.html.erb
<div id="<%= dom_id product_category %>">
  <p>
    <strong>Category:</strong>
    <%= product_category.name %>
  </p>

</div>
<% @products.each do |product| %>
<% if product_category.name == product.product_category.name %>
  <%= link_to product.name, product%>

<% end %>
<% end %>  

app/views/product_categories/edit.html.erb
<h1>Editing product category</h1>

<%= render "form", product_category: @product_category %>

<br>

<div>
  <%= link_to "Show this product category", @product_category %> |
  <%= link_to "Back to product categories", product_categories_path %>
</div>
  

app/views/product_categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Product categories</h1>

<div id="product_categories">
  <% @product_categories.each do |product_category| %>
    <%= render product_category %>
  <% end %>
</div>

<%= link_to "New product category", new_product_category_path %>
  

app/views/product_categories/new.html.erb
<h1>New product category</h1>

<%= render "form", product_category: @product_category %>

<br>

<div>
  <%= link_to "Back to product categories", product_categories_path %>
</div>
  

app/views/product_categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product_category %>


  